[package]
name = "dt"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "3.0", features = ["derive"] }
chrono = {version="0.4.19", features = ["unstable-locales"]}
timezone-abbreviations = "0.1.0"

[dev-dependencies]
chrono-tz = "0.6.0"
